language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11.7
# command to install dependencies
install:
  - "pip install -q -e ."
  - "pip install -q -r demo/requirements.txt"
  - "pip install -q Django==$DJANGO_VERSION"

# command to run tests
script: "cd demo && python manage.py makemigrations && python manage.py test plans"
